const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const hexes=YIJING_DATA.hexagrams;const byName=Object.fromEntries(hexes.map(h=>[h.name,h]));const byNum=Object.fromEntries(hexes.map(h=>[h.number,h]));const tri=YIJING_DATA.trigrams;const order=YIJING_DATA.trigramOrder;let lastResult=null;
function show(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));scrollTo(0,0)}
$$('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#installBtn').onclick=()=>$('#installDialog').showModal();$('#closeInstall').onclick=()=>$('#installDialog').close();
function isReady(h){return h.textStatus && h.textStatus.includes('已录入')}
function renderLibrary(){let q=$('#searchInput').value.trim();let f=$('#filterSelect').value;let list=hexes.filter(h=>(!q||h.name.includes(q)||String(h.number)===q)&& (f==='all'||(f==='ready'?isReady(h):!isReady(h))));$('#hexList').innerHTML=list.map(h=>`<button class="hex-card" onclick="openHex(${h.number})"><div class="hex-top"><div class="hex-symbol">${h.symbol}</div><div><div class="hex-name">第${h.number}卦 ${h.name}</div><div><span class="pill">${h.upperSymbol}${h.upper}上</span><span class="pill">${h.lowerSymbol}${h.lower}下</span><span class="pill ${isReady(h)?'ready':'pending'}">${isReady(h)?'原典已录入':'待校对'}</span></div></div></div></button>`).join('')||'<div class="card">没有找到匹配的卦。</div>'}
window.openHex=n=>{let h=byNum[n];$('#detailBox').innerHTML=`<div class="card detail-head"><div class="symbol">${h.symbol}</div><h2>第${h.number}卦 ${h.name}</h2><p>${h.upperSymbol}${h.upper}上 · ${h.lowerSymbol}${h.lower}下 · ${h.guaMeaning}</p><p><span class="pill ${isReady(h)?'ready':'pending'}">${h.quality}</span></p>${h.sourceUrl?`<p><a class="source-link" href="${h.sourceUrl}" target="_blank" rel="noopener">查看公开原文来源 ↗</a></p>`:''}</div><div class="card"><h3>卦辞</h3><p class="classic">${h.guaci}</p><p class="translation"><strong>译文：</strong>${h.guaciPlain||h.plain||'待精校补入。'}</p><div class="section"><h3>彖传</h3><p class="classic">${h.tuan||'待精校补入。'}</p><p class="translation"><strong>译文：</strong>${h.tuanPlain||'待精校补入。'}</p></div><div class="section"><h3>象传</h3><p class="classic">${h.xiang}</p><p class="translation"><strong>译文：</strong>${h.xiangPlain||'待精校补入。'}</p></div><div class="section"><h3>六爻</h3>${h.yao.map((y,i)=>`<div class="yao"><strong>${i+1}爻</strong><br><span class="classic">${y}</span><p class="translation"><strong>译文：</strong>${(h.yaoPlain&&h.yaoPlain[i])||h.linePlain[i]||'待精校补入。'}</p></div>`).join('')}</div><div class="section"><h3>白话学习提示</h3><p>${h.plain}</p></div><div class="section"><h3>我的学习笔记</h3><textarea id="noteText" rows="5" placeholder="写下你对本卦的理解……">${getNote(h.number)}</textarea><button class="primary" onclick="saveNote(${h.number})">保存笔记</button></div></div>`;show('detail')}
function getNote(n){return localStorage.getItem('note_'+n)||''}window.saveNote=n=>{localStorage.setItem('note_'+n,$('#noteText').value);alert('已保存学习笔记。')}
function modNum(n,m){let r=Number(n)%m;return r===0?m:r}function trigramByNum(n){return order[n-1]}function hexByCombo(upper,lower){return hexes.find(h=>h.upper===upper&&h.lower===lower)}function changedHex(h,line){let arr=[...h.lines];arr[line-1]=arr[line-1]?0:1;let lowerName=Object.keys(tri).find(k=>tri[k].lines.join('')===arr.slice(0,3).join(''));let upperName=Object.keys(tri).find(k=>tri[k].lines.join('')===arr.slice(3,6).join(''));return hexByCombo(upperName,lowerName)}
$('#calcBtn').onclick=()=>{let n1=$('#n1').value.trim(),n2=$('#n2').value.trim(),n3=$('#n3').value.trim();if(!n1||!n2||!n3){alert('请输入三组数字。');return}let u=trigramByNum(modNum(n1,8)),l=trigramByNum(modNum(n2,8)),line=modNum(n3,6);let h=hexByCombo(u,l),ch=changedHex(h,line);lastResult={id:crypto.randomUUID(),time:new Date().toISOString(),question:$('#question').value.trim(),n1,n2,n3,upper:u,lower:l,line,hex:h.number,changed:ch.number};renderResult(lastResult)};
function renderResult(r){let h=byNum[r.hex],ch=byNum[r.changed];$('#resultBox').innerHTML=`<div class="card"><h2>起卦结果</h2><div class="result-title"><div><div style="font-size:54px">${h.symbol}</div><strong>本卦<br>第${h.number}卦 ${h.name}</strong></div><div><div style="font-size:28px;margin:12px">动爻</div><strong>第${r.line}爻</strong></div><div><div style="font-size:54px">${ch.symbol}</div><strong>变卦<br>第${ch.number}卦 ${ch.name}</strong></div></div><div class="section"><h3>关联知识库</h3><p><strong>本卦卦辞：</strong>${h.guaci}</p><p><strong>动爻：</strong>${h.yao[r.line-1]}</p><p class="muted">${(h.yaoPlain&&h.yaoPlain[r.line-1])||h.linePlain[r.line-1]||''}</p><p><strong>变卦：</strong>${ch.name} ${ch.guaci}</p></div><div class="section"><h3>学习式解读</h3><p>${interpret(r,h,ch)}</p></div><label>我的当下理解 / 复盘备注<textarea id="reflection" rows="4"></textarea></label><button class="primary" onclick="saveRecord()">保存本次卜卦</button></div>`;}
function interpret(r,h,ch){let base=isReady(h)?h.plain:'本卦原典解释尚未完全录入，因此此处先按卦名、上下卦、动爻位置作学习式提示。';let lineHint=['事情还在萌芽，先观察与蓄势。','关系或资源开始显现，可寻求支持。','处在转折中的压力位，宜谨慎。','将进未进，重在试探与守正。','时位较成熟，可发挥影响力。','已接近极点，重在收束与防过度。'][r.line-1];return `${base} 本次动爻在第${r.line}爻，提示：${lineHint} 变卦为${ch.name}，可作为后续变化方向来观察。请结合所问之事，以“时机、位置、进退、风险、应对”五个角度复盘。`}
window.saveRecord=()=>{if(!lastResult)return;lastResult.reflection=$('#reflection').value.trim();let rec=getRecords();rec.unshift(lastResult);localStorage.setItem('yijing_records',JSON.stringify(rec));alert('已保存卜卦记录。');renderRecords();show('records')}
function getRecords(){try{return JSON.parse(localStorage.getItem('yijing_records')||'[]')}catch{return[]}}function renderRecords(){let rec=getRecords();$('#recordsList').innerHTML=rec.length?rec.map(r=>{let h=byNum[r.hex],ch=byNum[r.changed];return `<div class="record-card"><h3>${h.symbol} ${h.name} → ${ch.symbol} ${ch.name}</h3><p class="muted">${new Date(r.time).toLocaleString()} · 数字：${r.n1} / ${r.n2} / ${r.n3} · 动爻：${r.line}</p>${r.question?`<p><strong>所问：</strong>${esc(r.question)}</p>`:''}${r.reflection?`<p><strong>备注：</strong>${esc(r.reflection)}</p>`:''}<div class="record-actions"><button class="secondary" onclick="openHex(${h.number})">查看本卦</button><button class="danger" onclick="delRecord('${r.id}')">删除</button></div></div>`}).join(''):'<div class="card">还没有卜卦记录。</div>'}
window.delRecord=id=>{if(!confirm('删除这条记录？'))return;let rec=getRecords().filter(r=>r.id!==id);localStorage.setItem('yijing_records',JSON.stringify(rec));renderRecords()}
$('#exportBtn').onclick=()=>{let data={app:'我的易经｜学习与数字卦',exportedAt:new Date().toISOString(),records:getRecords(),notes:Object.keys(localStorage).filter(k=>k.startsWith('note_')).map(k=>[k,localStorage.getItem(k)])};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yijing-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click()}
$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{let data=JSON.parse(reader.result);if(data.records)localStorage.setItem('yijing_records',JSON.stringify(data.records));if(data.notes)data.notes.forEach(([k,v])=>localStorage.setItem(k,v));renderRecords();alert('导入完成。')};reader.readAsText(f)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#searchInput').oninput=renderLibrary;$('#filterSelect').onchange=renderLibrary;renderLibrary();renderRecords();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);
